### ISSUE TITLE
Freezing when playing to chromecast

### ISSUE THREAD

**Issue by sebstr1** [fabiospampinato/cliflix#12]
Tv starts, video plays for like 2 seconds, then audio & video freezes and never starts again even though the download continues and finishes. Same thing with any movie I select, download speed is high and good router with close distance (no walls) used.. How to fix this?

**Comment by fabiospampinato** [comment]
Unfortunately I don't have a chromecast for testing this.

Does streaming it to VLC work?

cliflix uses [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli) under the hood for streaming to chromecast, which uses this [logic](https://github.com/webtorrent/webtorrent-cli/blob/master/bin/cmd.js#L478) for doing it.

This is most probably a problem with webtorrent-cli itself.

**Comment by sebstr1** [comment]
Oh yes, VLC works perfectly, really cool!
