### ISSUE TITLE
Show the size of torrents

### ISSUE THREAD

**Issue by fbm-static** [fabiospampinato/cliflix#13]
It was a pleasure using this tool but in addition to the column for the number of peers, please also add a column indication each item's size.

**Comment by fabiospampinato** [comment]
It's already there, along with a column for the numbers of leechers and uploading date (which must be enabled via the configuration file):

![screen shot 2017-09-25 at 21 08 35](https://user-images.githubusercontent.com/1812093/30826147-bfecab3c-a235-11e7-984e-e2e167850a45.png)

It won't be displayed if there's not enough space available in the terminal.
