### ISSUE TITLE
Right path and name of the config file

### ISSUE THREAD

**Issue by nelsonmau** [fabiospampinato/cliflix#15]
it seems this `~/usr/lib/node_modules/cliflix/dist/config.js`

never found `clifix.js` mentioned in README

bye

**Comment by fabiospampinato** [comment]
@nelsonmau are you having troubles creating the configuration file?

It should be named `cliflix`**`.json`**, not **`.js`**

**Comment by nelsonmau** [comment]
Hi @fabiospampinato. 

I didn't find the file specified [here](https://github.com/fabiospampinato/cliflix#configuration), so I've modified `.../config.js`. Should I had to create it? 

tnx

**Comment by fabiospampinato** [comment]
> You can customize cliflix to your likings via a ~/.cliflix.json file. ~ is the path to your home directory.

You should have created that file instead, modifying the source isn't advisable because your changes will be reverted if you ever update the program.
