### ISSUE TITLE
how to use in windows

### ISSUE THREAD

**Issue by joshisameer343** [fabiospampinato/cliflix#16]

**Comment by fabiospampinato** [comment]
Are you having a problem with cliflix itself or you just don't know how to install and use packages with npm?

**Comment by joshisameer343** [comment]
i just don't know how to use it on windows....

**Comment by fabiospampinato** [comment]
I'm sorry but this is not the place for learning how to install and use NPM packages, a quick Google search would provide you with all the info that you need.
