### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by AAlakkad** [fabiospampinato/cliflix#17]
Hi,

I just installed cliflix, tried to search for "Tears of Steel" as in the gif demo, but I'm always getting `No titles found for "Tears of Steel", try again.` for any search query.

Is it something in the config I need to add?

**Comment by fabiospampinato** [comment]
You should try a different torrent provider, ThePirateBay (the default one) might be blocked from your location.

```
{
  "torrents": { // Torrents-related settings
    "providers": { // Torrents providers-related settings
      "available": ["1337x", "KickassTorrents", "Rarbg", "T411", "ThePirateBay", "Torrent9", "TorrentProject", "Torrentz2"], // Providers to list if none is active
      "active": "ThePirateBay" // Active provider
    }
  }
}
```

**Comment by stjepangolemac** [comment]
I get this too, no matter what I do with the providers I cannot find anything. Can you post the example of the modified config?

**Comment by fabiospampinato** [comment]
@stjepangolemac 

```
```

**Comment by fabiospampinato** [comment]
@stjepangolemac 

```
$ cat ~/.cliflix.json

{
  "torrents": { // Torrents-related settings
    "providers": { // Torrents providers-related settings
      "available": ["1337x", "KickassTorrents", "Rarbg", "T411", "ThePirateBay", "Torrent9", "TorrentProject", "Torrentz2"], // Providers to list if none is active
      "active": "1337x" // Active provider
    }
  }
}
```

You might need to change your DNS configuration.

**Comment by stjepangolemac** [comment]
My bad, needed to wrap providers field into torrents field. Thank you for the quick reply!
