### ISSUE TITLE
SyntaxError on Node 5.5

### ISSUE THREAD

**Issue by fiatjaf** [fabiospampinato/cliflix#2]
```
v5.5.0
fiatjaf@luke ~ [2]> ~/node_modules/bin/watch 'Jardim das Aflições'

Command failed: /bin/sh -c ./node_modules/.bin/magnet --rows 10 "Jardim das Aflições" 1
/home/fiatjaf/node_modules/lib/node_modules/@fabiospampinato/watch/node_modules/magnet-cli/app.js:24
let argv = minimist(process.argv.slice(2), {'--': true})
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by thawkins** [comment]
+1 got this on fedora 26 

[thawkins@timdev05 ~]$ uname -a
Linux timdev05 4.12.9-300.fc26.x86_64 #1 SMP Fri Aug 25 13:09:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[thawkins@timdev05 ~]$ more /etc/os-release 
NAME=Fedora
VERSION="26 (Workstation Edition)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation


[thawkins@timdev05 ~]$ node -v
v4.2.2


[thawkins@timdev05 ~]$ npm install -g @fabiospampinato/watch
npm WARN engine caporal@0.7.0: wanted: {"node":">= 4.4.5"} (current: {"node":"4.2.2","npm":"2.14.7"})
 
> spawn-sync@1.0.15 postinstall /home/thawkins/.nvm/versions/node/v4.2.2/lib/node_modules/@fabiospampinato/watch/node_modules/caporal/node_modules/tabtab/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> node postinstall
> caporal@0.7.0 postinstall /home/thawkins/.nvm/versions/node/v4.2.2/lib/node_modules/@fabiospampinato/watch/node_modules/caporal
> (test -f ./node_modules/husky/bin/install.js && node ./node_modules/husky/bin/install.js) || exit 0
-
> bufferutil@3.0.2 install /home/thawkins/.nvm/versions/node/v4.2.2/lib/node_modules/@fabiospampinato/watch/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info looking for local prebuild @ prebuilds/bufferutil-v3.0.2-node-v46-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/thawkins/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v46-linux-x64.tar.gz
prebuild-install http request GET https://github.com/websockets/bufferutil/releases/download/v3.0.2/bufferutil-v3.0.2-node-v46-linux-x64.tar.gz
prebuild-install http 200 https://github.com/websockets/bufferutil/releases/download/v3.0.2/bufferutil-v3.0.2-node-v46-linux-x64.tar.gz
prebuild-install info downloading to @ /home/thawkins/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v46-linux-x64.tar.gz.11364-2625995.tmp
prebuild-install info renaming to @ /home/thawkins/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v46-linux-x64.tar.gz
prebuild-install info unpacking @ /home/thawkins/.npm/_prebuilds/https-github.com-websockets-bufferutil-releases-download-v3.0.2-bufferutil-v3.0.2-node-v46-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/thawkins/.nvm/versions/node/v4.2.2/lib/node_modules/@fabiospampinato/watch/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/bufferutil/build/Release/bufferutil.node
prebuild-install info unpack required /home/thawkins/.nvm/versions/node/v4.2.2/lib/node_modules/@fabiospampinato/watch/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/bufferutil/build/Release/bufferutil.node successfully
prebuild-install info install Successfully installed prebuilt binary!
/home/thawkins/.nvm/versions/node/v4.2.2/bin/watch -> /home/thawkins/.nvm/versions/node/v4.2.2/lib/node_modules/@fabiospampinato/watch/dist/bin/index.js
@fabiospampinato/watch@1.1.0 /home/thawkins/.nvm/versions/node/v4.2.2/lib/node_modules/@fabiospampinato/watch
├── pify@3.0.0
├── open@0.0.5
├── lodash@4.17.4
├── chalk@2.1.0 (escape-string-regexp@1.0.5, supports-color@4.4.0, ansi-styles@3.2.0)
├── is-online@7.0.0 (p-timeout@1.2.0, got@6.7.1, p-any@1.1.0, public-ip@2.3.5)
├── inquirer@3.2.3 (ansi-escapes@2.0.0, rx-lite-aggregates@4.0.8, cli-width@2.2.0, through@2.3.8, rx-lite@4.0.8, figures@2.0.0, mute-stream@0.0.7, strip-ansi@4.0.0, string-width@2.1.1, run-async@2.3.0, cli-cursor@2.1.0, external-editor@2.0.4)
├── read-pkg-up@2.0.0 (find-up@2.1.0, read-pkg@2.0.0)
├── caporal@0.7.0 (fast-levenshtein@2.0.6, lodash.camelcase@4.3.0, micromist@1.0.2, chalk@1.1.3, bluebird@3.5.0, prettyjson@1.2.1, winston@2.3.1, cli-table2@0.2.0, tabtab@2.2.2)
├── magnet-cli@0.1.1 (minimist@1.2.0, request@2.81.0, cheerio@0.20.0)
└── webtorrent-cli@1.11.0 (clivas@0.2.0, winreg@1.2.4, network-address@1.1.2, prettier-bytes@1.0.4, mime@1.4.0, executable@4.1.0, minimist@1.2.0, vlc-command@1.1.1, create-torrent@3.29.2, parse-torrent@5.8.3, moment@2.18.1, dlnacasts@0.1.0, ecstatic@2.2.1, nodebmc@0.0.7, airplay-js@0.3.0, chromecasts@1.9.0, webtorrent@0.98.19)
[thawkins@timdev05 ~]$ watch
? What do you want to watch? Star Wreck

Command failed: /bin/sh -c ./node_modules/.bin/magnet --rows 10 "Star Wreck"
/home/thawkins/.nvm/versions/node/v4.2.2/lib/node_modules/@fabiospampinato/watch/node_modules/magnet-cli/app.js:24
let argv = minimist(process.argv.slice(2), {'--': true})
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

[thawkins@timdev05 ~]$

**Comment by fiatjaf** [comment]
@thawkins your error is totally different.

**Comment by dalhundal** [comment]
ha, hi Tim @thawkins ( we worked together at that place in the basement in Farringdon... )

**Comment by sknepal** [comment]
+1  happening on macOS Sierra as well. Node version: 4.4.7.

Command failed: /bin/sh -c ./node_modules/.bin/magnet --rows 10 "indiana jones" 1
/usr/local/lib/node_modules/@fabiospampinato/watch/node_modules/magnet-cli/app.js:24
let argv = minimist(process.argv.slice(2), {'--': true})
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by millette** [comment]
Looks like [magnet-cli](https://github.com/lucasem/magnet) (a dependency) requires node 6 and above.

**Comment by fabiospampinato** [comment]
Due to some dependencies that are being used the minimum required version is 6.0.0.
