### ISSUE TITLE
?

### ISSUE THREAD

**Issue by RomanAnthem** [fabiospampinato/cliflix#23]
Bypass leaf signature
install git

Otherwise cliflix does not works.

**Comment by fabiospampinato** [comment]
What are you talking about?

**Comment by RomanAnthem** [comment]
Tell people that you need bypass leaf_signature and install git.
Otherwise you can not install your cliflix. git is necessary.
Am I right ?

**Comment by fabiospampinato** [comment]
You don't need `git` installed. And what's `bypass leaf_signature` supposed to be?

**Comment by fabiospampinato** [comment]
> I am running node.js in windows, so I need install git.

Weird. 🤔 

> [Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE]

This is probably not an error caused by `cliflix` directly.

> P.S.: certo che parlare tra due catanesi in inglese .... ci voli facci.

😄

**Comment by RomanAnthem** [comment]
[Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE]
You are right. This is not an error caused by cliflix.

But I do not want install git. So, bye bye cliflix ?
Studying about. 
Wishes.
