### ISSUE TITLE
utf-8 Subtitle problem

### ISSUE THREAD

**Issue by rusmelezi** [fabiospampinato/cliflix#29]
When I choose Turkish subtitles Turkish charachters(ç,ö,ş,ü,İ) are look like question mark in triangle, I tested it with mpv and VLC, also downloaded the subtitle myself and tested it there were no problem.

**Comment by fabiospampinato** [comment]
Have you tried using the subtitles file cliflix downloads for you? I'm not sure how we can fix this, maybe this is a problem with [webtorrent](https://github.com/webtorrent/webtorrent-cli).

**Comment by rusmelezi** [comment]
Tried to use subtitle file and still charachters look like that.

**Comment by fabiospampinato** [comment]
Then I guess the subtitle file is not good.

> also downloaded the subtitle myself

and you're downloading another subtitle file here, is it possible?
