### ISSUE TITLE
Name Collision with 'watch' Utility

### ISSUE THREAD

**Issue by pvtmert** [fabiospampinato/cliflix#3]
it has nice name but collides with `watch` command/utility

here is the ref: https://linux.die.net/man/1/watch

you want might to add alias `just-watch` or `wtch` 

i am not saying change the name but it might brake some functionality of other apps fyi.

have a nice day!

**Comment by fabiospampinato** [comment]
Thanks for pointing that out, I wasn't aware of that.

Unfortunately as far as I know it's not possible to install a package with npm under an alias, so I guess I should find a better name for it. If anybody have any other ideas I'm all ears, I'd like it to be a short word, it would be better if "[command name] [movie name]" was a proper sentence.

**Comment by millette** [comment]
See https://docs.npmjs.com/files/package.json#bin foran example where cli.js is aliased to myapp:

```
{ "bin" : { "myapp" : "./cli.js" } }
```

**Comment by fabiospampinato** [comment]
@millette Yes, but I was thinking more about a `npm i -g package my-alias` command, which it's not possible. What you are suggesting basically changes the name of the binary everywhere, I'd prefer to also change the name of the package itself at that point.

**Comment by fabiospampinato** [comment]
I've renamed it to `cliflix`, that shouldn't cause any other problem of this sort.
