### ISSUE TITLE
UTF-8 Turkish Charachter Problem 

### ISSUE THREAD

**Issue by rusmelezi** [fabiospampinato/cliflix#30]
I submitted issue liked this months ago but I wasn't able to make tests and share that time apologize for that, finally I decided to submit this issue properly. 

Problem : UTF-8 Turkish charachters doesn't look like proper on every player(mpv,vlc etc.) with only cliflix.

Experiment:
With cliflix, subtitles was look like this:
https://ibb.co/c6M74TT

Then I used same resources(a video file which is directly downloaded by cliflix but I used SAME subtitle file but this time I downloaded it manually from opensubtitles.org ) and executed them with this command:

> `mpv video-file-downloaded-by-cliflix --sub-file same-subfile-downloaded-manually-from-opensub`

and subtitles was proper this time.  https://ibb.co/RB5nJ4B

 The problem is valid for every torrent(tested with several torrents). I think problem is originated from opensubtitle api because when I downloaded subfile manually subtitles was proper, how can we fix it for Turkish and other UTF-8 users ?

Apologize for typos I am not native English speaker.

**Comment by fabiospampinato** [comment]
>  but I used SAME subtitle file

> when I downloaded subfile manually subtitles was proper

Wait are you using the same subs file downloaded by cliflix or not?

I'm not sure how to fix this problem, maybe we are downloading/saving subtitles improperly? I'm not sure 🤔

**Comment by rusmelezi** [comment]
I didn’t use same sub file directly downloaded by cliflix that is not worked. I downloaded same subfile from opensubtitles.org manually and used it and that worked.

**Comment by rusmelezi** [comment]
Can you also test any popular movie/series/video etc. with Turkish subtitles ?

**Comment by fabiospampinato** [comment]
Sorry I don't really have to try to debug this, but if anybody would like to submit a PR for this I'd be happy to consider it 👍
